export const CONFIG_ENVIRONMENT = {
  LOCAL: 'local',
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
} as const;

export const DATABASE_KEY = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

export const JWT_KEY = {
  JWT_ACCESS_TOKEN_SECRET_KEY: 'JWT_ACCESS_TOKEN_SECRET_KEY',
  JWT_REFRESH_TOKEN_SECRET_KEY: 'JWT_REFRESH_TOKEN_SECRET_KEY',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_TTL: 'JWT_REFRESH_TOKEN_TTL',
} as const;

export const AWS_S3_KEY = {
  S3_ACCESS_KEY: 'S3_ACCESS_KEY',
  S3_SECRET_KEY: 'S3_SECRET_KEY',
  S3_BUCKET_REGION: 'S3_BUCKET_REGION',
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
  S3_BUCKET_URL: 'S3_BUCKET_URL',
} as const;

export const OAUTH_KEY = {
  KAKAO_GET_USER_URI: 'KAKAO_GET_USER_URI',
  KAKAO_AUTHORIZATION_KEY: 'KAKAO_AUTHORIZATION_KEY',
  KAKAO_SEARCH_KEYWORD_URI: 'KAKAO_SEARCH_KEYWORD_URI',
  KAKAO_MENU_URI: 'KAKAO_MENU_URI',
  KAKAO_SEARCH_IMAGE_URI: 'KAKAO_SEARCH_IMAGE_URI',
  KAKAO_SEARCH_IMAGE_MAX_SIZE: 'KAKAO_SEARCH_IMAGE_MAX_SIZE',
  GOOGLE_GET_USER_URI: 'GOOGLE_GET_USER_URI',
  NAVER_GET_USER_URI: 'NAVER_GET_USER_URI',
  APPLE_GET_USER_URI: 'APPLE_GET_USER_URI',
} as const;

export const REDIS_KEY = {
  REDIS_URL: 'REDIS_URL',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_TEMP_AUTH_TTL: 'REDIS_TEMP_AUTH_TTL',
  REDIS_LATEST_REVIEW_TTL: 'REDIS_LATEST_REVIEW_TTL',
  REDIS_LATEST_REVIEW_KEY: 'REDIS_LATEST_REVIEW_KEY',
  REDIS_TOP_REVIEWERS_TTL: 'REDIS_TOP_REVIEWERS_TTL',
  REDIS_TOP_REVIEWERS_KEY: 'REDIS_TOP_REVIEWERS_KEY',
  REDIS_CATEGORY_KEY: 'REDIS_CATEGORY_KEY',
  REDIS_LAST_CATEGORY_KEY: 'REDIS_LAST_CATEGORY_KEY',
  REDIS_PLACE_CATEGORY_KEY: 'REDIS_PLACE_CATEGORY_KEY',
  REDIS_LAST_PLACE_CATEGORY_KEY: 'REDIS_LAST_PLACE_CATEGORY_KEY',
  REDIS_PLACE_CATEGORY_TTL: 'REDIS_PLACE_CATEGORY_TTL',
  REDIS_INFINITE_TTL: 'REDIS_INFINITE_TTL',
} as const;

export const ENVIRONMENT_KEY = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  ...JWT_KEY,
  ...AWS_S3_KEY,
  ...OAUTH_KEY,
  ...REDIS_KEY,
} as const;
