name: CI

on:
  push:
    branches: [develop]
jobs:
  Build_and_Test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.18.2

      - name: Install Dependencies
        run: npm ci

      - name: Compile Backend-Server
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Download Test Environment file from S3
        run: aws s3 cp ${{ secrets.S3_TEST_ENV }} .env

      - name: Check .env file exists
        id: check-env
        run: |
          if [ -f .env ]; then
            echo "env-exists=true" >> $GITHUB_ENV
          else
            echo "env-exists=false" >> $GITHUB_ENV
          fi

      - name: Unit Test
        if: env.env-exists == 'true'
        run: npm run test:unit
